name: Generate and Deploy Allure Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Start ChromeDriver
        run: |
          # Start chromedriver in the background
          chromedriver --port=4444 &
          sleep 3 # give chromedriver time to start

      - name: Build and run tests with Maven
        run: |
          # Pass system properties to fix Chrome issues
          mvn clean test \
            -Dwebdriver.chrome.driver=$(which chromedriver) \
            -Dchrome.options="--no-sandbox,--headless=new,--disable-gpu,--disable-dev-shm-usage,--remote-allow-origins=*" \
            -Duser.data.dir=/tmp/chrome-data-$(date +%s)
        continue-on-error: true

      - name: Create gh-pages branch if not exists
        run: |
          git fetch
          if ! git ls-remote --heads origin gh-pages | grep gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout ${GITHUB_REF##*/}
          fi

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          gh_pages: gh-pages
          allure_report: allure-report
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
